const bgImages = {
	schoolDay: require("../assets/images/bg/School_Hallway_Day.jpg"),
	classroomDay: require("../assets/images/bg/Classroom_Day.jpg"),
	bedroomDay: require("../assets/images/bg/Bedroom_Day.jpg"),
	bedroomEvening: require("../assets/images/bg/Bedroom_Evening.jpg"),
	bedroomNight: require("../assets/images/bg/Bedroom_Night.jpg"),
	bedroomNightDark: require("../assets/images/bg/Bedroom_Night_Dark.jpg"),
	cafeteriaDay: require("../assets/images/bg/Cafeteria_Day.jpg"),
	cityAfternoon: require("../assets/images/bg/City_Afternoon.jpg"),
	cityMorning: require("../assets/images/bg/City_Morning.jpg"),
	cityNight: require("../assets/images/bg/City_Night.jpg"),
	cityRaining: require("../assets/images/bg/City_Raining.jpg"),
	kitchenDay: require("../assets/images/bg/Kitchen_Day.jpg"),
	kitchenNight: require("../assets/images/bg/Kitchen_Night.jpg"),
	livingroomDark: require("../assets/images/bg/Livingroom_Dark.jpg"),
	livingroomDay: require("../assets/images/bg/Livingroom_Day.jpg"),
	livingroomNight: require("../assets/images/bg/Livingroom_Night.jpg"),
	streetAutumnDay: require("../assets/images/bg/Street_Autumn_Day.jpg"),
	streetAutumnEvening: require("../assets/images/bg/Street_Autumn_Evening.jpg"),
	streetAutumnNight: require("../assets/images/bg/Street_Autumn_Night.jpg"),
	streetSpringDay: require("../assets/images/bg/Street_Spring_Day.jpg"),
	streetSpringEvening: require("../assets/images/bg/Street_Spring_Evening.jpg"),
	streetSpringNight: require("../assets/images/bg/Street_Spring_Night.jpg"),
	streetSpringRain: require("../assets/images/bg/Street_Spring_Rain.jpg"),
	streetSummerDay: require("../assets/images/bg/Street_Summer_Day.jpg"),
	streetSummerEvening: require("../assets/images/bg/Street_Summer_Evening.jpg"),
	streetSummerNight: require("../assets/images/bg/Street_Summer_Night.jpg"),
	streetSummerRain: require("../assets/images/bg/Street_Summer_Rain.jpg"),
	streetSummerStars: require("../assets/images/bg/Street_Summer_Stars.jpg"),
};

export default bgImages;
